export const GET_ALL_COMMENTS = "GET_ALL_COMMENTS";
export const ADD_NEW_COMMENT = "ADD_NEW_COMMENT";
export const UPDATE_COMMENT = "UPDATE_COMMENT";
export const ADD_NEW_REPLY = "ADD_NEW_REPLY";
